version: '3.4'

services:
  dockerweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

   dockerdesign:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat
